"""
Explainability models.

Provides the schema for human-readable insights generated by Gemini
based on deterministic scoring evidence.
"""

from __future__ import annotations

from typing import List
from uuid import UUID

from pydantic import Field

from app.models.base import AppBaseModel, IdentifiableMixin


class CandidateInsight(AppBaseModel):
    """
    Structured insights synthesized by Gemini from deterministic evidence.
    """
    why_ranked_here: str = Field(description="Summary of why the candidate received this overall score and rank.")
    top_strengths: List[str] = Field(description="Top 2-3 strengths matching the JD.")
    top_weaknesses: List[str] = Field(description="Top 2-3 missing elements or weaknesses.")
    matched_skills: List[str] = Field(description="Exact skills matched (carried over from scoring).")
    missing_skills: List[str] = Field(description="Exact skills missing (carried over from scoring).")
    interview_focus_areas: List[str] = Field(description="Suggested topics to dig into during an interview.")
    suggested_next_step: str = Field(description="Actionable next step (e.g. 'Schedule technical screen', 'Pass').")


class HiringRecommendationRecord(IdentifiableMixin):
    """
    Internal record linking the AI insight to a candidate and job.
    """
    analysis_job_id: UUID = Field(description="ID of the Analysis Job")
    candidate_id: UUID = Field(description="ID of the ResumeProfile")
    overall_score: float = Field(description="Overall score from Module 6")
    recommendation: str = Field(description="Rank/Recommendation level (e.g. Strong Fit)")
    insight: CandidateInsight = Field(description="The generated AI explanation.")


class HiringRecommendationRead(HiringRecommendationRecord):
    """
    API Response shape for the recommendation.
    """
    pass
